# Generated by Django 3.0.5 on 2021-11-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_name', models.CharField(max_length=200)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('avg_speed', models.IntegerField(blank=True, null=True)),
                ('temprature', models.IntegerField(blank=True, null=True)),
                ('fuel', models.CharField(choices=[('Full', 'Full'), ('Half', 'Half'), ('Empty', 'Empty')], default='Full', max_length=255, verbose_name='Fuel')),
                ('engine', models.CharField(choices=[('Full', 'Full'), ('Half', 'Half'), ('Empty', 'Empty')], default='Good', max_length=255, verbose_name='Engine')),
            ],
        ),
    ]
