# Generated by Django 3.0.5 on 2021-11-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='engine',
            field=models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], default='Good', max_length=255, verbose_name='Engine'),
        ),
    ]
